/**
*charts
*/
app.directive('lolChampionsCharts',function(){
    return{
        restrict:'E',
        templateUrl:'templates/base/general/charts.html',
        transclude:true,
        replace:true,
        scope:false,
        link:function(scope,element,attrs){
        },
        controller:function($scope){
        }
    }
});