/**
*rank
*/
app.directive('lolRank',function(){
    return{
        restrict:'E',
        templateUrl:'templates/base/rank.html',
        transclude:true,
        replace:true,
        scope:false,
        link:function(scope,element,attrs){
        },
        controller:function($scope,getApi){
			$("body").css("background-image","url('../images/otherbg.jpg')");
            getApi.getChallengerInfo().success(function(data){
                $scope.challengerInfo = data;
            });
        }
    }
});